// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {};

  config.name = 'Node-Express-Strap';

  config.dbname = 'nodeboilerstrap';

  config.sessionSecret = 'myprecious';

  config.port = 4000;

  config.someAPIkey = 'asdfasdfaksafaasdfa';

  module.exports = config;

}).call(this);
