// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Home',
      key: 'front',
      path: '/'
    }, {
      label: 'Profile',
      key: 'profile',
      path: '/profile'
    }, {
      label: 'About',
      key: 'about',
      path: '/about'
    }
  ];

  module.exports = links;

}).call(this);
